[package]
name = "blog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
walkdir = "2.5.0"
yaml-rust2 = "0.10.3"
quick-xml = "0.31"
pulldown-latex = "0.7.1"
pulldown-cmark = "0.13.1"
lumis = { version = "0.1.3", default-features = false, features = ["lang-html", "lang-latex", "lang-python", "lang-rust", "lang-haskell"] }

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]
